"""make input_type and input_data nullable in predictions

Revision ID: 21d0a8858285
Revises: c18263c84a15
Create Date: 2025-09-26 13:54:55.216520

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21d0a8858285"
down_revision = "c18263c84a15"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("predictions", "input_type", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("predictions", "input_data", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "predictions", "input_data", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "predictions", "input_type", existing_type=sa.TEXT(), nullable=False
    )
    # ### end Alembic commands ###
