"""set_user_extra_cap_default_to_zero

Revision ID: 845f18053bd1
Revises: fcca7c1dfadf
Create Date: 2025-10-01 13:49:59.923863

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "845f18053bd1"
down_revision = "fcca7c1dfadf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update existing NULL user_extra_cap values to 0 (0 means no overage allowed)
    # NULL will now mean unlimited overage
    op.execute(
        "UPDATE subscriptions SET user_extra_cap = 0 WHERE user_extra_cap IS NULL"
    )

    # Set the default value for the column
    op.alter_column("subscriptions", "user_extra_cap", server_default="0")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the default value
    op.alter_column("subscriptions", "user_extra_cap", server_default=None)
    # ### end Alembic commands ###
