"""add_stripe_customer_id_to_organizations

Revision ID: cd7e8ec3b144
Revises: 845f18053bd1
Create Date: 2025-10-01 15:57:52.037027

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd7e8ec3b144"
down_revision = "845f18053bd1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("stripe_customer_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "stripe_customer_id")
    # ### end Alembic commands ###
