"""add_cancel_at_period_end_to_subscriptions

Revision ID: fcca7c1dfadf
Revises: 03964c23b6c4
Create Date: 2025-10-01 00:28:04.638603

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fcca7c1dfadf"
down_revision = "03964c23b6c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column(
            "cancel_at_period_end", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "cancel_at_period_end")
    # ### end Alembic commands ###
