ENVIRONMENT=PROD
DATABASE_URL=${DATABASE_URL}
REDIS_URL=${REDIS_URL}

SUPABASE_URL=${SUPABASE_URL}
SUPABASE_KEY=${SUPABASE_KEY}
SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}

RESEND_API_KEY=${RESEND_API_KEY}

STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
